# Generated by Django 3.2.9 on 2022-03-09 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parasites',
            new_name='Parasite',
        ),
    ]
