# Generated by Django 3.2.9 on 2022-03-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_parasites_parasite'),
    ]

    operations = [
        migrations.AddField(
            model_name='parasite',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
