# Generated by Django 3.2.9 on 2022-03-11 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_parasite_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parasite',
            name='name',
        ),
    ]
